version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: on-failure
    build: .
    ports:
      - 3000:3000
    networks:
      - backend
  db:
    container_name: mysql
    build:
      context: ./db
    ports:
      - 3306:3306
    networks:
      - backend
networks: 
  backend:
